"""
Django settings for web_system project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# line-channel
CHANNEL_SECRET= "2041b308a40dd1e7d24bb7e457c6cf58" #你的 CHANNEL_SECRET
CHANNEL_ACCESS_TOKEN= "n0uv+rM5NDYaHqxixZQ/jAJ00RAzIQDf6I6KBNodbaXNX1xC17gxtKmfsZyVe/FVhFbLiSqKzuiClDdrJGbiggFad7tHP77dLj2n91oGpFHjTreFx71fQgzcG2voeNhoWP0jQBKffE0PzoRyPFvPJgdB04t89/1O/w1cDnyilFU=" #你的 CHANNEL_ACCESS_TOKEN

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-9#)t4w*%h^^p5f2jz@4#kre(yqo**=_8ed+9!+8ik$xl4oj6%q"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

STATICFILES_DIRS = (os.path.join(BASE_DIR,'static/'),)

ALLOWED_HOSTS = ['127.0.0.1','localhost','210c-218-161-97-197.ngrok-free.app']
CSRF_TRUSTED_ORIGINS = ["https://*.ngrok-free.app"]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "web_app",
    "django_bootstrap5",
    "line_bot_app",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "web_system.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR,"templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "web_system.wsgi.application"


# Send email constant
EMAIL_HOST = "smtp.gmail.com"

EMAIL_HOST_USER = "aa3741867@gmail.com"

EMAIL_HOST_PASSWORD = "geujwfjehzpfemyu"

EMAIL_PORT = "465"

EMAIL_USE_SSL = "True"

ADMINS = (('kingston', 'aa3741867@gmail.com'),)

MANAGERS = (('kingston', 'aa3741867@gmail.com'),)


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "zh-hant"

TIME_ZONE = "Asia/Taipei"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "/static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
