# Generated by Django 5.0 on 2024-01-21 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_app", "0002_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForgetPassword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checkemail", models.BooleanField(default=False)),
                (
                    "visitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web_app.visitor",
                    ),
                ),
            ],
            options={
                "db_table": "ForgetPassword",
            },
        ),
    ]
